name: Run Makefile Command

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Make
      run: sudo apt-get install make

    - name: Run say-hello
      run: make say-hello

