name: Run Makefile Command

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Run say-hello
      run: make say-hello
